#!/usr/bin/env python

import sys
import re

htmltags=['doctype','html','head','meta','script','style','body','div','span','href','img','class','table','tbody','thead','tfoot','form','input','code','button','caption','cite','col','pre']


def parseHTML(inputHTML):
	words={}
	with open(inputHTML,'r') as file:
		for line in file:
			line=re.sub("[^\w]"," ",line)
			line=line.split()
			for word in line:
				if len(str(word))<3:
					continue
				if word in htmltags:
					continue
				word=word.lower()
				if word in words.keys():
					words[word]+=1
				else:
					words[word]=1
	for key in words:
		print key+'\t'+str(words[key])

def main():
	if len(sys.argv)!=2:
		print "Usage: "+sys.argv[0]+" html_file"
		sys.exit()
	parseHTML(sys.argv[1])


if __name__=='__main__':
	main()
