#!/bin/bash
#Alex Wu
#CSE40822
#bigrams

hadoop jar $HADOOP_HOME/mapred/contrib/streaming/hadoop-*-streaming.jar	-input /users/edu_html/* -output /users/awu3/bigrams -mapper BigramsMap.py -file scripts/BigramsMap.py -reducer BigramsReduce.py -file scripts/BigramsReduce.py
